# Generated by Django 6.0.5 on 2026-05-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "size_sqm",
                    models.FloatField(blank=True, null=True, verbose_name="Größe (m²)"),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("full_sun", "Vollsonne"),
                            ("partial_shade", "Halbschatten"),
                            ("shade", "Schatten"),
                        ],
                        default="full_sun",
                        max_length=20,
                        verbose_name="Lage",
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("outdoor", "Freiland"),
                            ("greenhouse", "Gewächshaus"),
                        ],
                        default="outdoor",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
            ],
            options={
                "verbose_name": "Beet",
                "verbose_name_plural": "Beete",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vegetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruit", "Fruchtgemüse"),
                            ("leaf", "Blattgemüse"),
                            ("root", "Wurzelgemüse"),
                            ("bulb", "Zwiebelgemüse"),
                            ("legume", "Hülsenfrüchte"),
                            ("brassica", "Kohlgemüse"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "sunlight_requirement",
                    models.CharField(
                        choices=[
                            ("full_sun", "Vollsonne"),
                            ("partial_shade", "Halbschatten"),
                            ("shade", "Schatten"),
                        ],
                        default="full_sun",
                        max_length=20,
                        verbose_name="Lichtbedarf",
                    ),
                ),
                (
                    "water_requirement",
                    models.CharField(
                        choices=[
                            ("low", "Gering"),
                            ("medium", "Mittel"),
                            ("high", "Hoch"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Wasserbedarf",
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        blank=True,
                        help_text="z. B. humusreich, durchlässig, lehmig",
                        max_length=200,
                        verbose_name="Bodentyp",
                    ),
                ),
                (
                    "nutrient_demand",
                    models.CharField(
                        choices=[
                            ("low", "Schwachzehrer"),
                            ("medium", "Mittelzehrer"),
                            ("high", "Starkzehrer"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Nährstoffbedarf",
                    ),
                ),
                (
                    "indoor_start_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Voranzucht ab (Monat)"
                    ),
                ),
                (
                    "indoor_start_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Voranzucht bis (Monat)"
                    ),
                ),
                (
                    "sow_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Aussaat ab (Monat)"
                    ),
                ),
                (
                    "sow_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Aussaat bis (Monat)"
                    ),
                ),
                (
                    "plant_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pflanzung ab (Monat)"
                    ),
                ),
                (
                    "plant_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pflanzung bis (Monat)"
                    ),
                ),
                (
                    "harvest_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ernte ab (Monat)"
                    ),
                ),
                (
                    "harvest_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ernte bis (Monat)"
                    ),
                ),
                (
                    "gh_sow_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="GH Aussaat ab (Monat)"
                    ),
                ),
                (
                    "gh_sow_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="GH Aussaat bis (Monat)"
                    ),
                ),
                (
                    "gh_plant_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="GH Pflanzung ab (Monat)"
                    ),
                ),
                (
                    "gh_plant_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="GH Pflanzung bis (Monat)"
                    ),
                ),
                (
                    "gh_harvest_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="GH Ernte ab (Monat)"
                    ),
                ),
                (
                    "gh_harvest_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="GH Ernte bis (Monat)"
                    ),
                ),
                (
                    "saatgut_url",
                    models.URLField(
                        blank=True,
                        help_text="z. B. Bingenheimer Saatgut",
                        verbose_name="Saatgut-Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gemüsesorte",
                "verbose_name_plural": "Gemüsesorten",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BedPlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Jahr")),
                (
                    "planted_date",
                    models.DateField(blank=True, null=True, verbose_name="Pflanzdatum"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantings",
                        to="garden.bed",
                        verbose_name="Beet",
                    ),
                ),
                (
                    "vegetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantings",
                        to="garden.vegetable",
                        verbose_name="Gemüsesorte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beetbelegung",
                "verbose_name_plural": "Beetbelegungen",
                "ordering": ["-year", "bed", "vegetable"],
                "unique_together": {("bed", "vegetable", "year")},
            },
        ),
        migrations.CreateModel(
            name="FertilizingReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Intervall (Tage)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "last_fertilized",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zuletzt gedüngt"
                    ),
                ),
                (
                    "next_fertilizing",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nächstes Düngen"
                    ),
                ),
                (
                    "bed_planting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilizing_reminder",
                        to="garden.bedplanting",
                        verbose_name="Beetbelegung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Düngeerinnerung",
                "verbose_name_plural": "Düngeerinnerungen",
            },
        ),
        migrations.CreateModel(
            name="HerbTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "herb_name",
                    models.CharField(max_length=100, verbose_name="Kräutername"),
                ),
                ("benefit", models.TextField(verbose_name="Nutzen")),
                (
                    "vegetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="herb_tips",
                        to="garden.vegetable",
                        verbose_name="Gemüsesorte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kräuter-Tipp",
                "verbose_name_plural": "Kräuter-Tipps",
            },
        ),
        migrations.CreateModel(
            name="WateringReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Intervall (Tage)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "last_watered",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zuletzt gegossen"
                    ),
                ),
                (
                    "next_watering",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nächstes Gießen"
                    ),
                ),
                (
                    "weather_suppressed",
                    models.BooleanField(
                        default=False,
                        help_text="Wird in Iteration 3 durch Wetterlogik gesetzt",
                        verbose_name="Wetter-unterdrückt",
                    ),
                ),
                (
                    "bed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watering_reminder",
                        to="garden.bed",
                        verbose_name="Beet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gießerinnerung",
                "verbose_name_plural": "Gießerinnerungen",
            },
        ),
        migrations.CreateModel(
            name="SuccessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Begründung")),
                (
                    "avoid_after",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoid_before",
                        to="garden.vegetable",
                        verbose_name="Nicht nach dieser Sorte",
                    ),
                ),
                (
                    "vegetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="succession_notes",
                        to="garden.vegetable",
                        verbose_name="Gemüsesorte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fruchtfolge-Hinweis",
                "verbose_name_plural": "Fruchtfolge-Hinweise",
                "unique_together": {("vegetable", "avoid_after")},
            },
        ),
        migrations.CreateModel(
            name="NeighborRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("good", "Guter Nachbar"),
                            ("bad", "Schlechter Nachbar"),
                        ],
                        max_length=10,
                        verbose_name="Beziehungstyp",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Begründung")),
                (
                    "neighbor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbor_of",
                        to="garden.vegetable",
                        verbose_name="Nachbar",
                    ),
                ),
                (
                    "vegetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbor_relations",
                        to="garden.vegetable",
                        verbose_name="Gemüsesorte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nachbarschaftsbeziehung",
                "verbose_name_plural": "Nachbarschaftsbeziehungen",
                "unique_together": {("vegetable", "neighbor")},
            },
        ),
    ]
