# Generated by Django 6.0.5 on 2026-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bed",
            options={
                "ordering": ["name"],
                "verbose_name": "Gartenbeet",
                "verbose_name_plural": "Gartenbeete",
            },
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="category",
            field=models.CharField(
                choices=[
                    ("fruit", "Fruchtgemüse"),
                    ("leaf", "Blattgemüse"),
                    ("root", "Wurzelgemüse"),
                    ("bulb", "Zwiebelgemüse"),
                    ("legume", "Hülsenfrüchte"),
                    ("brassica", "Kohlgemüse"),
                    ("herb", "Kräuter"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=20,
                verbose_name="Kategorie",
            ),
        ),
    ]
